icons = "awesome"
theme = "nord-dark"

[[block]]
block = "external_ip"
format = "{country_flag}-{asn}-{country_code_iso3}-{region_code}-{city}-{ip}"

[[block]]
block = "net"
device = "eno1"
format = "{ip}{speed_down;K*b}{speed_up;K*b}"
interval = 5

[[block]]
block = "docker"
interval = 5
format = "{running}/{total}"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon} {used}/{total}"
alert_absolute = true
unit = "GB"
alert = 450
warning = 400

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "time"
interval = 5
format = "%a %m/%d %R"
